<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2015r4

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="agt xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:MapToModelLocExample_var25_create_rec">
		<xsl:param name="var24_current"/>
		<rec>
			<xsl:variable name="var1_ROWID">
				<xsl:if test="$var24_current/@ROW_ID">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var1_ROWID))) != 'false'">
				<xsl:attribute name="ROW_ID">
					<xsl:value-of select="string($var24_current/@ROW_ID)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var2_BLDGSCHEME">
				<xsl:if test="$var24_current/@BLDGSCHEME">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var2_BLDGSCHEME))) != 'false'">
				<xsl:attribute name="BLDGSCHEME">
					<xsl:value-of select="string($var24_current/@BLDGSCHEME)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var3_BLDGCODE">
				<xsl:if test="$var24_current/@BLDGCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var3_BLDGCODE))) != 'false'">
				<xsl:attribute name="BLDGCODE">
					<xsl:value-of select="string($var24_current/@BLDGCODE)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var4_OCCSCHEME">
				<xsl:if test="$var24_current/@OCCSCHEME">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var4_OCCSCHEME))) != 'false'">
				<xsl:attribute name="OCCSCHEME">
					<xsl:value-of select="string($var24_current/@OCCSCHEME)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var5_OCCCODE">
				<xsl:if test="$var24_current/@OCCCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var5_OCCCODE))) != 'false'">
				<xsl:attribute name="OCCCODE">
					<xsl:value-of select="string($var24_current/@OCCCODE)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var6_YEARBUILT">
				<xsl:if test="$var24_current/@YEARBUILT">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var6_YEARBUILT))) != 'false'">
				<xsl:attribute name="YEARBUILT">
					<xsl:value-of select="string($var24_current/@YEARBUILT)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var7_NUMSTORIES">
				<xsl:if test="$var24_current/@NUMSTORIES">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var7_NUMSTORIES))) != 'false'">
				<xsl:attribute name="NUMSTORIES">
					<xsl:value-of select="string($var24_current/@NUMSTORIES)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var8_POSTALCODE">
				<xsl:if test="$var24_current/@POSTALCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var8_POSTALCODE))) != 'false'">
				<xsl:attribute name="POSTALCODE">
					<xsl:value-of select="string($var24_current/@POSTALCODE)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var9_COUNTYCODE">
				<xsl:if test="$var24_current/@COUNTYCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var9_COUNTYCODE))) != 'false'">
				<xsl:attribute name="COUNTYCODE">
					<xsl:value-of select="string($var24_current/@COUNTYCODE)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var10_STATECODE">
				<xsl:if test="$var24_current/@STATECODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var10_STATECODE))) != 'false'">
				<xsl:attribute name="STATECODE">
					<xsl:value-of select="string($var24_current/@STATECODE)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var11_MODEL">
				<xsl:if test="$var24_current/@MODEL1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var11_MODEL))) != 'false'">
				<xsl:attribute name="MODEL1">
					<xsl:value-of select="string($var24_current/@MODEL1)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var12_MODEL">
				<xsl:if test="$var24_current/@MODEL2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var12_MODEL))) != 'false'">
				<xsl:attribute name="MODEL2">
					<xsl:value-of select="string($var24_current/@MODEL2)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var13_MODEL">
				<xsl:if test="$var24_current/@MODEL3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var13_MODEL))) != 'false'">
				<xsl:attribute name="MODEL3">
					<xsl:value-of select="string($var24_current/@MODEL3)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var14_MODEL">
				<xsl:if test="$var24_current/@MODEL4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var14_MODEL))) != 'false'">
				<xsl:attribute name="MODEL4">
					<xsl:value-of select="string($var24_current/@MODEL4)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var15_MODEL">
				<xsl:if test="$var24_current/@MODEL5">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var15_MODEL))) != 'false'">
				<xsl:attribute name="MODEL5">
					<xsl:value-of select="string($var24_current/@MODEL5)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var16_COVTIV">
				<xsl:if test="$var24_current/@COV1TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:variable name="var17_result">
				<xsl:choose>
					<xsl:when test="string((string($var24_current/@COV1TIV) &gt; string('0'))) != 'false'">
						<xsl:value-of select="'1'"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="'0'"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var16_COVTIV))) != 'false'">
				<xsl:attribute name="COV1">
					<xsl:value-of select="string($var17_result)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var18_COVTIV">
				<xsl:if test="$var24_current/@COV2TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:variable name="var19_result">
				<xsl:choose>
					<xsl:when test="string((string($var24_current/@COV2TIV) &gt; string('0'))) != 'false'">
						<xsl:value-of select="'1'"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="'0'"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var18_COVTIV))) != 'false'">
				<xsl:attribute name="COV2">
					<xsl:value-of select="string($var19_result)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var20_COVTIV">
				<xsl:if test="$var24_current/@COV3TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:variable name="var21_result">
				<xsl:choose>
					<xsl:when test="string((string($var24_current/@COV3TIV) &gt; string('0'))) != 'false'">
						<xsl:value-of select="'1'"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="'0'"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var20_COVTIV))) != 'false'">
				<xsl:attribute name="COV3">
					<xsl:value-of select="string($var21_result)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var22_COVTIV">
				<xsl:if test="$var24_current/@COV4TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:variable name="var23_result">
				<xsl:choose>
					<xsl:when test="string((string($var24_current/@COV4TIV) &gt; string('0'))) != 'false'">
						<xsl:value-of select="'1'"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="'0'"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var22_COVTIV))) != 'false'">
				<xsl:attribute name="COV4">
					<xsl:value-of select="string($var23_result)"/>
				</xsl:attribute>
			</xsl:if>
		</rec>
	</xsl:template>
	<xsl:template name="agt:MapToModelLocExample_var27_resultof_map">
		<xsl:param name="var26_current"/>
		<xsl:for-each select="$var26_current/rec">
			<xsl:call-template name="agt:MapToModelLocExample_var25_create_rec">
				<xsl:with-param name="var24_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template match="/">
		<root>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">C:/Users/Administrator/Desktop/git/Flamingo/Files/ValidationFiles/ModelLocExample.xsd</xsl:attribute>
			<xsl:for-each select="root">
				<xsl:call-template name="agt:MapToModelLocExample_var27_resultof_map">
					<xsl:with-param name="var26_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</root>
	</xsl:template>
</xsl:stylesheet>
