<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2015r4

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="agt xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:MapToCanLocExampleA_var38_create_rec">
		<xsl:param name="var37_current"/>
		<rec>
			<xsl:variable name="var1_ACCNTNUM">
				<xsl:if test="$var37_current/@ACCNTNUM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:if test="string(boolean(string($var1_ACCNTNUM))) != 'false'">
				<xsl:attribute name="ACCNTNUM">
					<xsl:value-of select="string($var37_current/@ACCNTNUM)"/>
				</xsl:attribute>
			</xsl:if>
			<xsl:variable name="var2_RISKNUM">
				<xsl:if test="$var37_current/@RISKNUM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="RISKNUM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var2_RISKNUM))) != 'false'">
						<xsl:value-of select="string($var37_current/@RISKNUM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var3_BLDGSCHEME">
				<xsl:if test="$var37_current/@BLDGSCHEME">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="BLDGSCHEME">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var3_BLDGSCHEME))) != 'false'">
						<xsl:value-of select="string($var37_current/@BLDGSCHEME)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var4_BLDGCODE">
				<xsl:if test="$var37_current/@BLDGCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="BLDGCODE">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var4_BLDGCODE))) != 'false'">
						<xsl:value-of select="string($var37_current/@BLDGCODE)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var5_OCCSCHEME">
				<xsl:if test="$var37_current/@OCCSCHEME">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="OCCSCHEME">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var5_OCCSCHEME))) != 'false'">
						<xsl:value-of select="string($var37_current/@OCCSCHEME)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var6_OCCCODE">
				<xsl:if test="$var37_current/@OCCCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="OCCCODE">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var6_OCCCODE))) != 'false'">
						<xsl:value-of select="string($var37_current/@OCCCODE)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var7_YEARBUILT">
				<xsl:if test="$var37_current/@YEARBUILT">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="YEARBUILT">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var7_YEARBUILT))) != 'false'">
						<xsl:value-of select="string($var37_current/@YEARBUILT)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var8_NUMSTORIES">
				<xsl:if test="$var37_current/@NUMSTORIES">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="NUMSTORIES">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var8_NUMSTORIES))) != 'false'">
						<xsl:value-of select="string($var37_current/@NUMSTORIES)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('1')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var9_NUMRISKS">
				<xsl:if test="$var37_current/@NUMRISKS">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="NUMRISKS">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var9_NUMRISKS))) != 'false'">
						<xsl:value-of select="string($var37_current/@NUMRISKS)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('1')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var10_POSTALCODE">
				<xsl:if test="$var37_current/@POSTALCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="POSTALCODE">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var10_POSTALCODE))) != 'false'">
						<xsl:value-of select="string($var37_current/@POSTALCODE)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var11_COUNTYCODE">
				<xsl:if test="$var37_current/@COUNTYCODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COUNTYCODE">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var11_COUNTYCODE))) != 'false'">
						<xsl:value-of select="string($var37_current/@COUNTYCODE)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var12_STATECODE">
				<xsl:if test="$var37_current/@STATECODE">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="STATECODE">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var12_STATECODE))) != 'false'">
						<xsl:value-of select="string($var37_current/@STATECODE)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var13_MODEL">
				<xsl:if test="$var37_current/@MODEL1">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="MODEL1">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var13_MODEL))) != 'false'">
						<xsl:value-of select="string($var37_current/@MODEL1)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var14_MODEL">
				<xsl:if test="$var37_current/@MODEL2">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="MODEL2">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var14_MODEL))) != 'false'">
						<xsl:value-of select="string($var37_current/@MODEL2)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var15_MODEL">
				<xsl:if test="$var37_current/@MODEL3">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="MODEL3">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var15_MODEL))) != 'false'">
						<xsl:value-of select="string($var37_current/@MODEL3)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var16_MODEL">
				<xsl:if test="$var37_current/@MODEL4">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="MODEL4">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var16_MODEL))) != 'false'">
						<xsl:value-of select="string($var37_current/@MODEL4)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var17_MODEL">
				<xsl:if test="$var37_current/@MODEL5">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="MODEL5">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var17_MODEL))) != 'false'">
						<xsl:value-of select="string($var37_current/@MODEL5)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var18_COVTIV">
				<xsl:if test="$var37_current/@COV1TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV1TIV">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var18_COVTIV))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV1TIV)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var19_COVTIV">
				<xsl:if test="$var37_current/@COV2TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV2TIV">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var19_COVTIV))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV2TIV)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var20_COVTIV">
				<xsl:if test="$var37_current/@COV3TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV3TIV">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var20_COVTIV))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV3TIV)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var21_COVTIV">
				<xsl:if test="$var37_current/@COV4TIV">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV4TIV">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var21_COVTIV))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV4TIV)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var22_COVDED">
				<xsl:if test="$var37_current/@COV1DED">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV1DED">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var22_COVDED))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV1DED)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var23_COVDED">
				<xsl:if test="$var37_current/@COV2DED">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV2DED">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var23_COVDED))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV2DED)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var24_COVDED">
				<xsl:if test="$var37_current/@COV3DED">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV3DED">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var24_COVDED))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV3DED)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var25_COVDED">
				<xsl:if test="$var37_current/@COV4DED">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV4DED">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var25_COVDED))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV4DED)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var26_COVLIM">
				<xsl:if test="$var37_current/@COV1LIM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV1LIM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var26_COVLIM))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV1LIM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var27_COVLIM">
				<xsl:if test="$var37_current/@COV2LIM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV2LIM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var27_COVLIM))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV2LIM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var28_COVLIM">
				<xsl:if test="$var37_current/@COV3LIM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV3LIM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var28_COVLIM))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV3LIM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var29_COVLIM">
				<xsl:if test="$var37_current/@COV4LIM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COV4LIM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var29_COVLIM))) != 'false'">
						<xsl:value-of select="string($var37_current/@COV4LIM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var30_COMBDED">
				<xsl:if test="$var37_current/@COMBDED">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COMBDED">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var30_COMBDED))) != 'false'">
						<xsl:value-of select="string($var37_current/@COMBDED)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var31_COMBLIM">
				<xsl:if test="$var37_current/@COMBLIM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="COMBLIM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var31_COMBLIM))) != 'false'">
						<xsl:value-of select="string($var37_current/@COMBLIM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var32_SITEDED">
				<xsl:if test="$var37_current/@SITEDED">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="SITEDED">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var32_SITEDED))) != 'false'">
						<xsl:value-of select="string($var37_current/@SITEDED)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var33_SITELIM">
				<xsl:if test="$var37_current/@SITELIM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="SITELIM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var33_SITELIM))) != 'false'">
						<xsl:value-of select="string($var37_current/@SITELIM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var34_SUBLIMGROUP">
				<xsl:if test="$var37_current/@SUBLIMGROUP">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="SUBLIMGROUP">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var34_SUBLIMGROUP))) != 'false'">
						<xsl:value-of select="string($var37_current/@SUBLIMGROUP)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var35_SUBLIMDED">
				<xsl:if test="$var37_current/@SUBLIMDED">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="SUBLIMDED">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var35_SUBLIMDED))) != 'false'">
						<xsl:value-of select="string($var37_current/@SUBLIMDED)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
			<xsl:variable name="var36_SUBLIMLIM">
				<xsl:if test="$var37_current/@SUBLIMLIM">
					<xsl:value-of select="'1'"/>
				</xsl:if>
			</xsl:variable>
			<xsl:attribute name="SUBLIMLIM">
				<xsl:choose>
					<xsl:when test="string(boolean(string($var36_SUBLIMLIM))) != 'false'">
						<xsl:value-of select="string($var37_current/@SUBLIMLIM)"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:value-of select="string('0')"/>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:attribute>
		</rec>
	</xsl:template>
	<xsl:template name="agt:MapToCanLocExampleA_var40_resultof_map">
		<xsl:param name="var39_current"/>
		<xsl:for-each select="$var39_current/rec">
			<xsl:call-template name="agt:MapToCanLocExampleA_var38_create_rec">
				<xsl:with-param name="var37_current" select="."/>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>
	<xsl:template match="/">
		<root>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">C:/Users/Administrator/Desktop/git/Flamingo/Files/ValidationFiles/CanLocExampleA.xsd</xsl:attribute>
			<xsl:for-each select="root">
				<xsl:call-template name="agt:MapToCanLocExampleA_var40_resultof_map">
					<xsl:with-param name="var39_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</root>
	</xsl:template>
</xsl:stylesheet>
